name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  client:
    name: Client
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          commit-message: Compiled client
          branch: deploy
